# Generated by Django 4.0.5 on 2022-07-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMvt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Familiares',
        ),
    ]
